#
# PROGRAM: z1861588_project2
# AUTHOR:  Noah Flores
#


labtrain: z1861588_project2.cpp
	g++ -g -ansi -pedantic -Wall -std=c++14 z1861588_project2.cpp -pthread -o z1861588_project2

clean:
	rm -f *.o z1861588_project2