#
# PROGRAM: z1861588_project4
# AUTHOR:  Noah Flores
#


labtrain: z1861588_project4.cpp
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 z1861588_project4.cpp -pthread -o z1861588_project4

clean:
	rm -f *.o z1861588_project4