#
# PROGRAM: z1861588_project5
# AUTHOR:  Noah Flores
#

all: z1861588_project5 z1861588_project5_p2

z1861588_project5: z1861588_project5.cpp
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 z1861588_project5.cpp -lpthread -o z1861588_project5

z1861588_project5_p2: z1861588_project5_p2.cpp
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 z1861588_project5_p2.cpp -lpthread -o z1861588_project5_p2
clean:
	rm -f *.o z1861588_project5 z1861588_project5_p2

	