#
# PROGRAM: z1861588_project1
# AUTHOR:  Noah Flores
#


labtrain: z1861588_project1.cpp
	g++ -g -ansi -pedantic -Wall -std=c++14 z1861588_project1.cpp -pthread -o z1861588_project1

clean:
	rm -f *.o z1861588_project1